import React from 'react';
import BlogPostLayout from '../../layouts/BlogPostLayout';

const ArchitecturePost: React.FC = () => {
  return (
    <BlogPostLayout
      title="The Invisible Engine: Architecture Deep Dive"
      date="2024-02-10"
      readTime="12 min read"
      tags={['Architecture', 'React', 'DevOps']}
    >
      <p>I built this platform not just as a portfolio, but as a proof-of-concept for the systems thinking I apply to every project. It runs on an automated continuous deployment pipeline engineered for zero-maintenance overhead and fast performance.</p>

      <p>Here is the technical breakdown of how this platform operates, from source code to edge delivery.</p>

      <h2>1. The Core Architecture: Source vs Distribution</h2>
      <p>Most projects mix source code and build artifacts in a single repository. I separate them cleanly.</p>

      <h3>The Problem</h3>
      <p>GitHub Pages serves static content. Modern web development (React, TypeScript, Vite) requires a build step. Managing build artifacts (<code>dist/</code>) in the same repo as source code pollutes the git history and creates merge conflicts.</p>

      <h3>The Solution: Repository Separation</h3>
      <p>I set up a Dual-Repository Strategy:</p>
      <ul>
        <li><strong>Source Core:</strong> Private repository containing TypeScript source, React components, Vite configuration, and styling.</li>
        <li><strong>Distribution Layer:</strong> Public repository containing only the optimized, minified production assets generated by the build pipeline.</li>
      </ul>
      <p>This separation keeps the public repository completely clean while private source history remains encapsulated.</p>

      <h2>2. The Frontend Stack: React + Vite + Framer Motion</h2>
      <p>The user interface is a state-driven client application.</p>

      <h3>Sticky Parallax Architecture</h3>
      <p>To make the hero transition impactful, I used CSS <code>position: sticky</code> combined with calculated container heights and physics-based motion hooks in Framer Motion.</p>

      <h2>3. The Deployment Pipeline: GitHub Actions CI/CD</h2>
      <p>Changes are deployed automatically. I do not manually build or upload files. The pipeline is defined in a standard GitHub Actions workflow file.</p>

      <h3>The Pipeline Sequence</h3>
      <p>Every time code is pushed to the <code>main</code> branch of the source repository, the following automated sequence triggers:</p>
      <ol>
        <li><strong>Environment Provisioning:</strong> A clean Linux container is initialized and the latest source code is checked out.</li>
        <li><strong>Dependency Resolution:</strong> <code>npm ci</code> ensures deterministic package installations from <code>package-lock.json</code>.</li>
        <li><strong>Build Verification:</strong> <code>npm run build</code> runs TypeScript type checking (<code>tsc -b</code>) and Vite bundling (tree-shaking, minification, CSS extraction).</li>
        <li><strong>Cross-Repository Deployment:</strong> An SSH deploy key authenticates with the distribution repository, pushing production assets directly to the edge CDN.</li>
      </ol>

      <pre><code>{`- name: Deploy to Distribution Repo
  uses: peaceiris/actions-gh-pages@v3
  with:
    deploy_key: \${{ secrets.DEPLOY_KEY }}
    external_repository: <target-repo>
    publish_branch: main
    publish_dir: ./dist`}</code></pre>

      <h2>4. Quality Standards & Verification</h2>
      <p>Every build undergoes automated verification before going live:</p>
      <ul>
        <li><strong>Static Type Safety:</strong> TypeScript strict mode ensures zero untyped variables.</li>
        <li><strong>Build Verification:</strong> Any build error or syntax issue stops the deployment immediately.</li>
        <li><strong>Automated CDN Deployment:</strong> Once verified, global CDNs update in under two minutes.</li>
      </ul>

      <p>This automated setup allows rapid iteration with zero manual deployment overhead.</p>
    </BlogPostLayout>
  );
};

export default ArchitecturePost;
